# Generated by Django 5.2.12 on 2026-05-23 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knockoutfixture',
            name='match_leg2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ko_fixture_leg2', to='core.match'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='ko_progression',
            field=models.CharField(choices=[('SINGLE', 'Single Leg KO'), ('AGGREGATE', 'Two Legs Aggregate'), ('GOLDEN_GOAL', 'Golden Goal (Single Leg)')], default='SINGLE', help_text='Progression rule for Knockout matches.', max_length=15),
        ),
        migrations.AddField(
            model_name='tournament',
            name='league_legs',
            field=models.IntegerField(default=1, help_text='Number of times each team plays each other (for League format).'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
