# Generated by Django 5.2.12 on 2026-04-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fantasypick_is_sub_player_injury_weeks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
