# Generated by Django 5.2.12 on 2026-04-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_team_logo_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyteam',
            name='formation',
            field=models.CharField(default='433', max_length=3),
        ),
    ]
