# Generated by Django 5.2.12 on 2026-04-09 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fantasyteam_formation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasypick',
            name='purchase_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='bank',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='free_transfers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='points_hit',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='core.gameweek')),
                ('player_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='core.player')),
                ('player_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='core.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
