# Generated by Django 5.2.12 on 2026-04-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fantasypick_purchase_price_fantasyteam_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasypick',
            name='is_vice_captain',
            field=models.BooleanField(default=False),
        ),
    ]
