# Generated by Django 5.2.12 on 2026-05-22 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_squadapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squadapplication',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='squadapplication',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='squadapplication',
            name='player3',
        ),
        migrations.AddField(
            model_name='squadapplication',
            name='formation',
            field=models.CharField(default='442', max_length=10),
        ),
        migrations.CreateModel(
            name='SquadPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starter', models.BooleanField(default=True)),
                ('position_order', models.IntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='core.squadapplication')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.player')),
            ],
            options={
                'ordering': ['-is_starter', 'player__position', 'position_order'],
            },
        ),
    ]
