# Generated by Django 5.2.12 on 2026-05-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_squadapplication_player1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadapplication',
            name='team_name',
            field=models.CharField(default='My Squad', max_length=100),
        ),
    ]
