# Generated by Django 5.2.12 on 2026-05-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_squadapplication_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadapplication',
            name='total_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
